quarkus.log.level=INFO
quarkus.jib.base-jvm-image=eclipse-temurin:21
quarkus.container-image.insecure=true
quarkus.container-image.registry=localhost:5001
quarkus.container-image.build=true
quarkus.container-image.push=
quarkus.micrometer.export.json.enabled=true
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.path=metrics/prometheus
quarkus.smallrye-health.extensions.enabled=true
quarkus.kubernetes.namespace=gruppe8-tcc
quarkus.kubernetes.name=gruppe8-tcc-audit-service
quarkus.kubernetes.replicas=1

