apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-tcc
  labels:
    name: gruppe8-tcc

---

apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-traffic-light-devices
  labels:
    name: gruppe8-traffic-light-devices

---

apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-shared-services
  labels:
    name: gruppe8-shared-services


---

apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-auth-services
  labels:
    name: gruppe8-auth-services