apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-tcc
  labels:
    name: gruppe8-tcc
    trust-ca: iv-ssas
---
apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-traffic-light-devices
  labels:
    name: gruppe8-traffic-light-devices
    trust-ca: iv-ssas
---
apiVersion: v1
kind: Namespace
metadata:
  name: gruppe8-shared-services
  labels:
    name: gruppe8-shared-services
    trust-ca: iv-ssas
