---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: task4-gruppe8-location-validator-cert
  namespace: gruppe8-shared-services
spec:
  isCA: false
  commonName: location-validator.svc.cluster.local
  subject:
    organizations:
      - Gruppe 8
    organizationalUnits:
      - Task 4
  secretName: task4-gruppe8-location-validator-tls
  usages:
    - server auth
    - client auth # Required for mTLS
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - location-validator
    - location-validator.gruppe8-shared-services
    - location-validator.gruppe8-shared-services.svc
    - location-validator.gruppe8-shared-services.svc.cluster.local
    - gruppe8-location-validator
    - gruppe8-location-validator.gruppe8-shared-services
    - gruppe8-location-validator.gruppe8-shared-services.svc
    - gruppe8-location-validator.gruppe8-shared-services.svc.cluster.local
    - tcc.test # For Ingress
  issuerRef:
    name: ha1-gruppe8-krzysztoflagowski-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
