# Logging configuration
quarkus.log.level=INFO

# Since we use Java 21, we need to specify a Docker image
quarkus.jib.base-jvm-image=eclipse-temurin:21

# We use our own local Docker registry and not Docker Hub
quarkus.container-image.insecure=true
quarkus.container-image.registry=localhost:5001
quarkus.container-image.build=true
quarkus.container-image.push=

# General Kubernetes deployment configuration
quarkus.micrometer.export.json.enabled=true
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.path=metrics/prometheus

# Enable liveness and readiness probes
quarkus.smallrye-health.extensions.enabled=true

# Kubernetes configuration
quarkus.kubernetes.namespace=gruppe8-shared-services
quarkus.kubernetes.name=gruppe8-location-validator
quarkus.kubernetes.replicas=1
# No Ingress - internal service only (accessed via Service Discovery)

