apiVersion: v1
kind: Secret
metadata:
  name: task5-gruppe8-tcc-state-controller-secret
type: Opaque
stringData:
  CLIENT_ID: tcc-state-controller
  CLIENT_SECRET: MEb3nfjgTGkEHiZs8NugXxKTf2UqHdVC
---
apiVersion: v1
kind: Secret
metadata:
  name: task5-gruppe8-tcc-priority-service-secret
type: Opaque
stringData:
  CLIENT_ID: tcc-priority-service
  CLIENT_SECRET: ORzb7Qc6FxG82m1GJjDTwPZmcmwNtPJb
---
apiVersion: v1
kind: Secret
metadata:
  name: task5-gruppe8-tcc-status-service-secret
type: Opaque
stringData:
  CLIENT_ID: tcc-status-service
  CLIENT_SECRET: u7dV5aMSxMpRrGL2BezDnMf1uQFIULkQ