# Logging configuration
quarkus.log.level=INFO

# Since we use Java 21, we need to specify a Docker image
quarkus.jib.base-jvm-image=eclipse-temurin:21

# We use our own local Docker registry and not Docker Hub
quarkus.container-image.insecure=true
quarkus.container-image.registry=localhost:5001
quarkus.container-image.build=true
quarkus.container-image.push=

# General Kubernetes deployment configuration
quarkus.micrometer.export.json.enabled=true
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.path=metrics/prometheus

# Enable liveness and readiness probes
quarkus.smallrye-health.extensions.enabled=true

# Kubernetes configuration
quarkus.kubernetes.namespace=gruppe8-shared-services
quarkus.kubernetes.name=gruppe8-time-service
quarkus.kubernetes.replicas=1
# No Ingress - internal service only (accessed via Service Discovery)

# Mount the Certificates from Cert Manager to microservice
quarkus.kubernetes.secret-volumes.tls.secret-name=task4-gruppe8-time-service-tls
quarkus.kubernetes.mounts.tls.name=tls
quarkus.kubernetes.mounts.tls.path=/etc/tls
quarkus.kubernetes.mounts.tls.read-only=true

# Setup Quarkus TLS Registry, using pem store of Cert Manager
quarkus.tls.http.key-store.pem.0.cert=/etc/tls/tls.crt
quarkus.tls.http.key-store.pem.0.key=/etc/tls/tls.key
quarkus.tls.http.trust-store.pem.certs=/etc/tls/ca.crt

# Require client certificates
quarkus.http.tls-configuration-name=http
quarkus.http.ssl.client-auth=required
quarkus.http.insecure-requests=disabled

# Set management interface to 0.0.0.0 with port 9000 and HTTPS
quarkus.management.enabled=true
quarkus.management.host=0.0.0.0
quarkus.management.port=9000
quarkus.management.tls-configuration-name=http

quarkus.kubernetes.startup-probe.http-action-scheme=HTTPS
quarkus.kubernetes.liveness-probe.http-action-scheme=HTTPS
quarkus.kubernetes.readiness-probe.http-action-scheme=HTTPS

quarkus.kubernetes.startup-probe.http-action-port=9000
quarkus.kubernetes.liveness-probe.http-action-port=9000
quarkus.kubernetes.readiness-probe.http-action-port=9000

#Set SSL Port
quarkus.http.ssl-port=8443

# Expose TLS port in generated k8s manifests
quarkus.kubernetes.ports.https.container-port=8443


#set oidc stuff 
quarkus.oidc.auth-server-url=http://keycloak-service.keycloak.svc.cluster.local:8080/keycloak/realms/group8-task5
quarkus.oidc.discovery-enabled=true

quarkus.oidc.application-type=service

quarkus.oidc.roles.role-claim-path=resource_access/time-service/roles

quarkus.oidc.roles.source=accesstoken